### PR TITLE
Custom option fixService to force a service url

### PR DESCRIPTION
**Pull request by yvesago**
This could be useful when application is used behind a proxy  or other similar cases

### CODE REVIEW

**Comment by geoffgarside** [comment]
Can you give an example of how this would be used? Would #16 offer similar functionality?

**Comment by yvesago** [comment]
Thanks for your reply.
The new urlScheme  looks nice but don't resolve this trouble.
urlScheme manage to fix CAS server URLs and fixService aims to fix client service URL.

I have an application server behind an apache proxy which manage SSL cert. 
Now "service" is create from the internal application server URL.
But the CAS server need to validate service from the public https url which can not be find without an option entry. 
fixService can also be used when distributed applications behind a load balancer need to validate same service.

I will merge and submit a new PR in few days.

**Comment by geoffgarside** [comment]
So is your (*http.Request).URL passed to your handler not that of the public https url?

**Comment by yvesago** [comment]
Sorry to not be clear. It's an other special case.
Now in go-cas, requestURL build the service URL with r *http.Request so, for a private application, "service" will be "http://myprivate:7777/protected/service" or http://localhost:7777/...
Instead of sending "http://myprivate:7777/protected/service" as the service to be registered by the CAS,
fixService can send "https://mypublic.dom/protected/service" 
Without fixService, the CAS server will redirect to  "http://myprivate:7777/protected/service?ticket=XXXXX" that will fail when private application and CAS server are not in the same network and ticket is send in clear text. With fixService, ticket will be send to the main proxy.

**Comment by geoffgarside** [comment]
Does the frontend HTTPS service pass headers like

- X-Forwarded-For
- X-Forwarded-Proto
- Host

to the backend service which is handling the request?

Can the frontend service not rewrite the "http://myprivate:7777/" part of the URL? Something like nginx `proxy_redirect` directive?

Wondering if theres a more conventional way to resolve this, say teaching `requestURL()` about more than just `X-Forwarded-Proto`.

**Comment by yvesago** [comment]
When I made some tests, I'm quit sure that X-Forwarded-Proto was missing on a apache 2.4 proxy.
I will retry ....

**Comment by geoffgarside** [comment]
Are you using the mod_proxy_http module in Apache 2.4, it looks like that can pass `X-Forwarded-Host` as well as For and Server, though not Proto. So we could add `X-Forwarded-Host` to `requestURL()` function. It looks like `X-Forwarded-Proto` would need to be set by a `RequestHeaders` directive in the Apache config.

**Comment by geoffgarside** [comment]
Though if its being handled in a SSL enabled VirtualHost block, then

```
RequestHeader set X-Forwarded-Proto "https"
```

in that block should be enough to add it into the request for the client to pick up.

**Comment by yvesago** [comment]
I miss this point. You are absolutely right !
Your X-Forwarded-Host and the RequestHeader work perfectly. You can forget this PR.
Thanks for your work.

**Pull request closed without merging**
